namespace TalesOfYonder.LegacyEngine.Gfx {

public enum MainGfxEnum {
    GameMenuPane,
    CharacterSheetPane,
    TeamOverviewPane,
    TalkPane,
    SpellPane,
    DoorMagicLock,
    ChestMagicLock,
    BookPane,
    ScrollPane,
    CaveDoorClosed,
    CaveDoorOpened,
    BarrelClosed,
    BarrelOpened,
    BedBack,
    BedFront,
    BedLeft,
    BedRight,
    BrickStairsUp,
    BrickStairsDown,
    BrickWall,
    BrickPortal,
    MountainBrown1,
    MountainBrown2,
    MountainBrownCaveEntrance,
    CaveLadder,
    CaveWall,
    ChestBackClosed,
    ChestBackOpen,
    ChestFrontClosed,
    ChestFrontOpen,
    ChestRightOpen,
    ChestLeftOpen,
    ChestSide,
    StoneGate,
    CaveEntry,
    MountainBlack1,
    MountainBlack2,
    MountainBlackCaveEntrance,
    PillarStone,
    MageOrbCutscene,
    HandsOrbCutscene,
    FireTrap,
    MagicTrap,
    StoneItem,
    BrickSecretDoorClosed,
    BrickSecretDoorOpened,
    StoneSecretDoorClosed,
    StoneSecretDoorOpened,
    Stalagmite,
    StalagmiteStalactite,
    StoneStairsUp,
    StoneStairsDown,
    StoneWall,
    StonePortal,
    TreeDeadSwamp,
    TableFood,
    Torch,
    TreeSingle,
    TreeForest,
    BrickDoorClosed,
    BrickDoorOpened,
    StoneDoorClosed,
    StoneDoorOpened,
    PillarWood,
    CavePortal,
    Quartz,
    QuartzDoorClosed,
    QuartzDoorOpen,
    QuartzPortal,
    DimensionalDoorClosed,
    DimensionalDoorOpen,
    SpikeTrap,
    PoisonTrap,
    CutsceneDoor1, // different palette, though
    CutsceneDoor2, // -||-
    CutsceneDoor3, // -||-
    CutsceneDoor4, // -||-
    CutsceneDoor5, // -||-
    CutsceneDoor6, // -||-
    ShotArrowsFront,
    ShotArrowsBack,
    ShotStones,
    ShotFlasksThrown,
    ShopInn,
    ShopSupplies,
    ShopWeapons,
    ShopSmith,
    ShopGuildRed,
    ShopHealer,
    ShopAlchemist,
    ShopGuildBlue,
    ShopJeweller,
    ShopEnchanter,
    ShopTrainer,
    HutChallenge,
    ShotShrapnel,
    ShotHalo,
    ShotSpark,
    ShotFlame,
    ShotIcicle,
    ComingSoon,
}

}
